<?php

/**
 * @file
 * Handle weather logic.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function weather_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.weather':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple "Weather" module.');
      return $output;
  }
  return NULL;
}
