weather.settings:
  type: config_object
  label: Settings of the module
  mapping:
    weather_api_endpoint:
      type: url
      label: The API endpoint used for requests. Like http://api.openweathermap.org/data/2.5/weather.
    weather_api_key:
      type: string
      label: The API key used for requests.
    weather_default_country_code:
      type: select
      label: The country code used for default.
    weather_default_city:
      type: string
      label: The city used for default.
